### ISSUE TITLE
Unable to get working with Next.js App Router on Netlify

### ISSUE THREAD

**Issue by dmorda** [tomer-yechiel/pino-sentry-transport#229]
**Describe the bug**
When using pino-sentry-transport with Next.js (14.x) it works in development mode, but when I deploy it to Netlify I get an error that says it's unable to determine transport target for "pino-sentry-transport".

```
Aug 7, 09:49:49 PM: a8a9ff79 ERROR   ⨯ Error: unable to determine transport target for "pino-sentry-transport"
    at fixTarget (/var/task/node_modules/pino/lib/transport.js:159:13)
    at /var/task/node_modules/pino/lib/transport.js:97:17
    at Array.map (<anonymous>)
    at transport (/var/task/node_modules/pino/lib/transport.js:94:59)
    at normalizeArgs (/var/task/node_modules/pino/lib/tools.js:316:16)
    at pino (/var/task/node_modules/pino/pino.js:90:28)
    at 40200 (/var/task/.next/server/chunks/739.js:1242:120)
    at t (/var/task/.next/server/webpack-runtime.js:1:143)
    at 32395 (/var/task/.next/server/chunks/142.js:792:2462)
    at t (/var/task/.next/server/webpack-runtime.js:1:143)
```

I realize this may not be a bug and it may be just that I'm mis-understanding how to get it working. Here's how I have it setup.

```
// logger.ts
import pino from 'pino';

// These are pulled from process.env.
import {nodeEnvironment, sentryDsn, sentryEnvironment} from '@/env';

const logger = pino(
    {
        level: 'info',
        transport: {
          targets: [
            {
              target: 'pino-sentry-transport',
              options: {
                sentry: {
                  dsn: sentryDsn,
                  environment: sentryEnvironment,
                },
                withLogRecord: true,
                tags: ['id'],
                context: ['hostname'],
                minLevel: 40,
                expectPinoConfig: true,
              },
            },
          ],
        },
      },
);

export default logger;
```

```
// next.config.mjs
/** @type {import('next').NextConfig} */

const nextConfig = {
  webpack: (config) => {
    config.externals.push('pino-sentry-transport');
    return config;
  },
  experimental: {
    serverComponentsExternalPackages: ['pino', 'pino-pretty', 'pino-sentry-transport'],
  },
};

export default nextConfig;
```

What am I missing?

**Comment by tomer-yechiel** [comment]
@dmorda  is this issue still relevant?

**Comment by dmorda** [comment]
No, you can close it.
